
## MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: my-mongodb
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  type: NodePort
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      nodePort: 30002
---
## MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - name: mongodb
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
          - name: mongodb-storage 
            mountPath: /data/db
      volumes:
        - name: mongodb-storage
          emptyDir: {}